### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by apokalupsis** [Qwant/firefox-extension#3]
Hi,
Sorry is not a firefox-extension bug, but I can not access to the website for report the bug.
The website dont load, JS error:

TypeError: LanguageHelper.getCountry(...) is undefined                                 bootstrap.js:23

My local storage contains:

user :"{"isLogged":false,"userSetting":{"lang":{"shorthand":"fr","code":"fr_fr","country":"FR","name":"Français","continent":"EUROPE"},"continentKey":"EUROPE","regionKey":"FR","showTrends":1,"showFavicon":true,"enableSuggest":true,"targetBlank":true,"searchMode":0,"completeUrl":true,"safeSearch":1},"fieldsValidity":{},"version":21}"

Thanks.

**Comment by ssavinel** [comment]
Hello !
Sorry about the inconvenience and don't worry about reaching us here, we are glad you did !
There have been many changes in the past days, possibly your issue has been fixed ?
We tried to repeat your bug using a copy of the local Storage you provided, but we never encountered it.
If you still have this bug, do you have any more informations you can provide ?

Thanks for your time!

**Comment by apokalupsis** [comment]
OK, thanks, yes still have.

the file I get:
200 https://www.qwant.com/web
304 style.css?1457603774844
304 templates.js?1457603774844
304 app.js?1457603774844
304 bootstrap.js?1457603774844
304 background.png?1457603774844

the var splitTerritory is  ["zh", "HK"]
LanguageHelper.getCountry("FR") return france JSON
LanguageHelper.getCountry("HK") return undefined

I am in china (good alternative to google)

**Comment by apokalupsis** [comment]
Is Fix thanks.
